ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "public"
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod-http01"
  hosts: 
    - plantuml.csie404-111.mlc.app
    #- host: "uml.csie.mlc.app"
      #paths:
      #- "/"
  tls:
    - hosts: 
      - plantuml.csie404-111.mlc.app
      secretName: plantuml-csie404-111-tls
autoscaling:
  enabled:
  minReplicas: 1
  maxReplicas: 3
